# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fe59081b223b56886086c8e1bb011259d86661b74f2a3ab34cdccc605c25ebb50bf2171f3591ff2e48617babd8951c97a0e8f36eaf4f98ad20ae97e0cfa4a3d

test:
  secret_key_base: 7377d594d6fb695f40cf60f933bb6f1adf2ac48152ad82f0185be3e2db8fdb204a0327ea491754100603185178618c59cfbf60fc5f6c71049a5410dfd98c9c91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
